### ISSUE TITLE
TracerComms: Permission denied

### ISSUE THREAD

**Issue by andres-leon** [kasparsd/raspi-solar-tracer-logger#1]
Hello,
Thank you for sharing your code and expertise. I would appreciate it if you could tell me what permissions are needed in order for TracerComms to work and be able to read the GPIO pins from the RBPi. I am getting the error:

`sh: 1: TracerComms: Permission denied`

whenever I run it from /usr/bin/TracerComms.

I have already granted execute permission
`-rwxr-xr-x 1 root root 19456 Mar 28 22:02 TracerComms`

but the error remains. Any help would be much appreciated! Thank you.

**Comment by kasparsd** [comment]
@andres-leon Does it work with `sudo`?

```
$ sudo ./TracerComms
```

For some reason the serial port `/dev/ttyAMA0` is not readable by all users. This seems like a generic Raspberry Pi issue.

**Comment by andres-leon** [comment]
Thank you for your response! Sorry, I was at work all day and couldn't test your solution.

When I run the command i get no result. If I apply the `--debug` option I get the following:

```
Using port 22
Baud Rate 9600
Sent 0 bytes: AA 55 AA 55 AA 55 EB 90 EB 90 EB 90 16 A0 00 B1 A7 7F
```
Not sure how to go from here. Your advice is much appreciated!
